---
# Deploy core infrastructure services to the control plane nodes
- name: Deploy Infrastructure Services
  hosts: k8s_master_init
  become: yes
  become_user: "{{ k8s_username }}"
  vars:
    k8s_username: "{{ ansible_user }}"
  tasks:
    # Create dedicated namespaces for infrastructure components
    - name: Create infrastructure namespaces
      shell: |
        kubectl create namespace argocd || true
        kubectl create namespace traefik || true
        kubectl create namespace cert-manager || true
      args:
        chdir: "/home/{{ k8s_username }}"

    # Apply node affinity to make sure infrastructure components run on control plane
    - name: Create infrastructure node affinity configuration
      copy:
        dest: "/home/{{ k8s_username }}/infrastructure-affinity.yml"
        content: |
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: infrastructure-affinity
            namespace: argocd
          data:
            # This template can be used in your ArgoCD app manifests
            controlPlaneAffinity: |
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: node-role.kubernetes.io/control-plane
                        operator: Exists
              tolerations:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
                effect: PreferNoSchedule
        owner: "{{ k8s_username }}"
        group: "{{ k8s_username }}"
        mode: '0644'

    - name: Apply infrastructure affinity configuration
      shell: |
        kubectl apply -f /home/{{ k8s_username }}/infrastructure-affinity.yml
      args:
        chdir: "/home/{{ k8s_username }}"

    # Deploy ArgoCD to the control plane nodes
    - name: Install ArgoCD
      shell: |
        # Add the ArgoCD Helm repository
        kubectl create namespace argocd || true
        
        cat <<EOF > /home/{{ k8s_username }}/argocd-values.yaml
        server:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
          tolerations:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: PreferNoSchedule
        controller:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
          tolerations:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: PreferNoSchedule
        repoServer:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
          tolerations:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: PreferNoSchedule
        applicationSet:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
          tolerations:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: PreferNoSchedule
        redis:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
          tolerations:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: PreferNoSchedule
        resources:
          limits:
            cpu: 300m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 300Mi
        EOF
        
        # Apply ArgoCD installation using kubectl (using official manifests for Pi compatibility)
        kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
        
        # Patch resources to ensure they run on control plane
        kubectl patch deployment argocd-server -n argocd --patch "$(cat <<EOF
        spec:
          template:
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: node-role.kubernetes.io/control-plane
                        operator: Exists
              tolerations:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
                effect: PreferNoSchedule
        EOF
        )"
        
        kubectl patch deployment argocd-repo-server -n argocd --patch "$(cat <<EOF
        spec:
          template:
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: node-role.kubernetes.io/control-plane
                        operator: Exists
              tolerations:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
                effect: PreferNoSchedule
        EOF
        )"
        
        kubectl patch deployment argocd-application-controller -n argocd --patch "$(cat <<EOF
        spec:
          template:
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: node-role.kubernetes.io/control-plane
                        operator: Exists
              tolerations:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
                effect: PreferNoSchedule
        EOF
        )"
        
        kubectl patch deployment argocd-redis -n argocd --patch "$(cat <<EOF
        spec:
          template:
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: node-role.kubernetes.io/control-plane
                        operator: Exists
              tolerations:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
                effect: PreferNoSchedule
        EOF
        )"
      args:
        chdir: "/home/{{ k8s_username }}"
      
    # Deploy Traefik as Ingress Controller to the control plane
    - name: Install Traefik Ingress Controller
      shell: |
        kubectl create namespace traefik || true
        
        # Create Traefik CRDs first
        kubectl apply -f https://raw.githubusercontent.com/traefik/traefik/v2.10.4/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
        
        # Create Traefik RBAC resources
        cat <<EOF > /home/{{ k8s_username }}/traefik-rbac.yaml
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: traefik-ingress
          namespace: traefik
        ---
        kind: ClusterRole
        apiVersion: rbac.authorization.k8s.io/v1
        metadata:
          name: traefik-ingress
        rules:
          - apiGroups:
              - ""
            resources:
              - services
              - endpoints
              - secrets
            verbs:
              - get
              - list
              - watch
          - apiGroups:
              - extensions
              - networking.k8s.io
            resources:
              - ingresses
              - ingressclasses
            verbs:
              - get
              - list
              - watch
          - apiGroups:
              - extensions
              - networking.k8s.io
            resources:
              - ingresses/status
            verbs:
              - update
          - apiGroups:
              - traefik.containo.us
            resources:
              - middlewares
              - middlewaretcps
              - ingressroutes
              - ingressroutetcps
              - tlsoptions
              - tlsstores
              - serverstransports
            verbs:
              - get
              - list
              - watch
        ---
        kind: ClusterRoleBinding
        apiVersion: rbac.authorization.k8s.io/v1
        metadata:
          name: traefik-ingress
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: traefik-ingress
        subjects:
          - kind: ServiceAccount
            name: traefik-ingress
            namespace: traefik
        EOF
        
        kubectl apply -f /home/{{ k8s_username }}/traefik-rbac.yaml
        
        # Create Traefik deployment and service
        cat <<EOF > /home/{{ k8s_username }}/traefik-deployment.yaml
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: traefik
          namespace: traefik
          labels:
            app: traefik
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: traefik
          template:
            metadata:
              labels:
                app: traefik
            spec:
              serviceAccountName: traefik-ingress
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: node-role.kubernetes.io/control-plane
                        operator: Exists
              tolerations:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
                effect: PreferNoSchedule
              containers:
                - name: traefik
                  image: traefik:v2.10.4
                  args:
                    - --api.insecure=true
                    - --accesslog
                    - --entrypoints.web.address=:80
                    - --entrypoints.websecure.address=:443
                    - --providers.kubernetescrd
                    - --providers.kubernetesingress
                    - --log.level=INFO
                  resources:
                    limits:
                      cpu: 200m
                      memory: 300Mi
                    requests:
                      cpu: 100m
                      memory: 150Mi
                  ports:
                    - name: web
                      containerPort: 80
                    - name: websecure
                      containerPort: 443
                    - name: dashboard
                      containerPort: 8080
        ---
        apiVersion: v1
        kind: Service
        metadata:
          name: traefik
          namespace: traefik
        spec:
          type: NodePort
          ports:
            - name: web
              port: 80
              targetPort: web
              nodePort: 32080
            - name: websecure
              port: 443
              targetPort: websecure
              nodePort: 32443
            - name: dashboard
              port: 8080
              targetPort: dashboard
              nodePort: 32808
          selector:
            app: traefik
        ---
        apiVersion: traefik.containo.us/v1alpha1
        kind: IngressRoute
        metadata:
          name: traefik-dashboard
          namespace: traefik
        spec:
          entryPoints:
            - web
          routes:
          - match: Host(`traefik.local`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
            kind: Rule
            services:
            - name: traefik
              port: 8080
        EOF
        
        kubectl apply -f /home/{{ k8s_username }}/traefik-deployment.yaml
      args:
        chdir: "/home/{{ k8s_username }}"

    # Deploy cert-manager to the control plane
    - name: Install cert-manager
      shell: |
        kubectl create namespace cert-manager || true
        
        # Apply cert-manager using the official manifests
        kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.14.3/cert-manager.yaml
        
        # Patch deployments to ensure they run on control plane
        for deployment in cert-manager cert-manager-cainjector cert-manager-webhook; do
          kubectl patch deployment $deployment -n cert-manager --patch "$(cat <<EOF
        spec:
          template:
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: node-role.kubernetes.io/control-plane
                        operator: Exists
              tolerations:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
                effect: PreferNoSchedule
        EOF
          )"
        done
      args:
        chdir: "/home/{{ k8s_username }}"
      
    # Display access information
    - name: Create information summary for infrastructure services
      copy:
        dest: "/home/{{ k8s_username }}/infrastructure-access-info.txt"
        content: |
          # Kubernetes Infrastructure Services Access Information
          
          ## ArgoCD
          - Access URL: http://[any-control-plane-node]:32080/argocd (after configuring in Traefik)
          - Default username: admin
          - Get password with: kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
          
          ## Traefik Ingress Controller
          - HTTP Port: 32080
          - HTTPS Port: 32443
          - Dashboard: http://[any-control-plane-node]:32808/dashboard/
          
          ## Cert-Manager
          - Deployed and running in cert-manager namespace
          - Create ClusterIssuer or Issuer resources to begin using Let's Encrypt
        owner: "{{ k8s_username }}"
        group: "{{ k8s_username }}"
        mode: '0644'
      
    - name: Display infrastructure access information
      shell: |
        echo "=== INFRASTRUCTURE SERVICES DEPLOYMENT COMPLETE ==="
        echo ""
        echo "ArgoCD password: $(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d)"
        echo ""
        echo "For more details, see ~/infrastructure-access-info.txt"
      register: access_info
      
    - name: Show access information
      debug:
        msg: "{{ access_info.stdout_lines }}"