---
- name: Kubernetes Worker Node Setup (Lenovo M920Q)
  hosts: k8s_workers_x86
  become: yes
  vars:
    k8s_version: "1.29"
    k8s_username: "{{ ansible_user }}"

  tasks:
    - name: Wait for apt locks to be released
      shell: |
        while lsof /var/lib/dpkg/lock-frontend >/dev/null 2>&1 || lsof /var/lib/apt/lists/lock >/dev/null 2>&1 || lsof /var/cache/apt/archives/lock >/dev/null 2>&1 || lsof /var/lib/dpkg/lock >/dev/null 2>&1; do
          echo "Waiting for apt lock to be released..."
          sleep 5
        done
      changed_when: false
      
    - name: Fix package management
      shell: |
        rm -rf /var/lib/dpkg/updates/*
        touch /var/lib/dpkg/status
        mkdir -p /var/lib/dpkg/info
        mkdir -p /var/lib/dpkg/updates
        dpkg --clear-avail
        apt-get update --fix-missing
        apt-get install -f -y
        apt-get clean
        dpkg --configure -a
      changed_when: true
      ignore_errors: yes
      
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - curl
          - apt-transport-https
          - ca-certificates
          - gnupg
          - lsb-release
          - software-properties-common
        state: present
        
    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
        
    - name: Install containerd from Docker repo
      apt:
        name: containerd.io
        state: present
        update_cache: yes
        
    - name: Create containerd configuration directory
      file:
        path: /etc/containerd
        state: directory
        mode: '0755'
        
    - name: Configure containerd
      shell: |
        containerd config default | sudo tee /etc/containerd/config.toml > /dev/null
        sudo sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml
      args:
        creates: /etc/containerd/config.toml
        
    - name: Configure containerd with optimized settings for x86
      copy:
        dest: /etc/containerd/config.toml
        content: |
          version = 2
          [plugins]
            [plugins."io.containerd.grpc.v1.cri"]
              sandbox_image = "registry.k8s.io/pause:3.9"
              [plugins."io.containerd.grpc.v1.cri".containerd]
                default_runtime_name = "runc"
                snapshotter = "overlayfs"
                [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
                  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
                    runtime_type = "io.containerd.runc.v2"
                    [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
                      SystemdCgroup = true
          [metrics]
            address = "127.0.0.1:1338"
            grpc_histogram = false
        mode: '0644'
        
    - name: Restart containerd
      systemd:
        name: containerd
        state: restarted
        enabled: yes
        daemon_reload: yes
        
    - name: Create Kubernetes apt keyring directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
    
    - name: Add Kubernetes apt key
      shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      args:
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    
    - name: Add Kubernetes apt repository
      shell: echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
      args:
        creates: /etc/apt/sources.list.d/kubernetes.list
    
    - name: Update apt cache after adding Kubernetes repo
      apt:
        update_cache: yes
    
    - name: Install Kubernetes components
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
    
    - name: Hold Kubernetes packages
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl
    
    - name: Load kernel modules
      shell: |
        modprobe overlay
        modprobe br_netfilter
      changed_when: true
    
    - name: Set up required sysctl params
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1
        mode: '0644'
    
    - name: Apply sysctl parameters
      shell: sysctl --system
      changed_when: true
    
    - name: Disable swap
      shell: |
        swapoff -a
        sed -i '/swap/d' /etc/fstab
      changed_when: true
    
    - name: Configure kubelet for high performance
      copy:
        dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
        content: |
          [Service]
          Environment="KUBELET_EXTRA_ARGS=--eviction-hard=memory.available<1Gi,nodefs.available<10%,nodefs.inodesFree<5% --system-reserved=memory=500Mi,cpu=500m --kube-reserved=memory=500Mi,cpu=500m"
        mode: '0644'
      register: kubelet_conf
      
    - name: Create systemd directory for kubelet
      file:
        path: /etc/systemd/system/kubelet.service.d
        state: directory
        mode: '0755'

    - name: Enable and start kubelet
      systemd:
        name: kubelet
        state: restarted
        enabled: yes
        daemon_reload: yes
      when: kubelet_conf.changed
        
    - name: Update all packages
      apt:
        update_cache: yes
        upgrade: full
        autoremove: yes
        autoclean: yes
      register: apt_upgrade
        
    - name: Optimize kernel parameters for worker node
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
      with_items:
        - { name: 'kernel.panic', value: '10' }
        - { name: 'kernel.panic_on_oops', value: '1' }
        - { name: 'vm.overcommit_memory', value: '1' }
        - { name: 'vm.panic_on_oom', value: '0' }
        - { name: 'net.ipv4.tcp_slow_start_after_idle', value: '0' }
        - { name: 'net.core.somaxconn', value: '65535' }
        - { name: 'net.ipv4.tcp_max_syn_backlog', value: '32768' }
        - { name: 'net.core.rmem_max', value: '16777216' }
        - { name: 'net.core.wmem_max', value: '16777216' }
        - { name: 'fs.inotify.max_user_watches', value: '1048576' }
        - { name: 'fs.file-max', value: '2097152' }
        
    - name: Install useful tools
      apt:
        name:
          - htop
          - iotop
          - iftop
          - nmon
          - sysstat
        state: present
        
    - name: Reboot node if needed
      reboot:
        msg: "Rebooting after system configuration"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: apt_upgrade.changed