---
- name: Initialize Kubernetes Master Node
  hosts: k8s_master
  become: yes
  vars:
    k8s_username: "{{ ansible_user }}"
  tasks:
    - name: Initialize Kubernetes cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address={{ ansible_host }}
      register: kubeadm_init
      args:
        creates: /etc/kubernetes/admin.conf
    
    - name: Create .kube directory for user
      file:
        path: "/home/{{ k8s_username }}/.kube"
        state: directory
        owner: "{{ k8s_username }}"
        group: "{{ k8s_username }}"
        mode: '0755'
      
    - name: Copy kube config for user
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "/home/{{ k8s_username }}/.kube/config"
        remote_src: yes
        owner: "{{ k8s_username }}"
        group: "{{ k8s_username }}"
        mode: '0600'
    
    - name: Install Flannel network addon
      become: yes
      become_user: "{{ k8s_username }}"
      shell: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
      args:
        chdir: "/home/{{ k8s_username }}"
        
    - name: Generate join command for worker nodes
      shell: kubeadm token create --print-join-command
      register: join_command
    
    - name: Save join command to a file
      local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join_command.sh"
      become: no

- name: Join Worker Nodes to Cluster
  hosts: k8s_workers
  become: yes
  vars:
    k8s_username: "{{ ansible_user }}"
  tasks:
    - name: Copy join command from local to worker nodes
      copy:
        src: ./join_command.sh
        dest: /tmp/join_command.sh
        mode: '0755'
      
    - name: Join the Kubernetes cluster
      shell: sh /tmp/join_command.sh
      register: join_output
      args:
        creates: /etc/kubernetes/kubelet.conf
    
    - name: Remove join command file
      file:
        path: /tmp/join_command.sh
        state: absent